[package]
name = "ksbh-modules-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
http = { workspace = true }
smol_str = { workspace = true }
ksbh-core = { path = "../ksbh-core/" }
ksbh-modules-abi = { path = "../ksbh-modules-abi/" }
thiserror = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tracing = { workspace = true }
proptest = { workspace = true }
