{{- if .Values.cookieKeySecret.create }}
{{- $secret_name := include "ksbh.cookieKeySecretName" . }}
{{- $secret_key := .Values.cookieKeySecret.key }}
{{- $namespace := .Release.Namespace }}
{{- $existing_secret := lookup "v1" "Secret" $namespace $secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ksbh.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $secret_key }}: {{- if $existing_secret }}
    {{ index $existing_secret.data $secret_key | quote }}
  {{- else }}
    {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
