#!/usr/bin/env bash
#MISE description="Build shared UI CSS and docs CSS"
#MISE tools={deno="latest"}
#MISE dir="./docs"
#MISE sources=["docs/deno.json", "docs/deno.lock", "docs/package.json", "docs/css/base.css", "crates/ksbh-ui/static/css/shared.css"]

set -euo pipefail

deno install --allow-scripts --node-modules-dir=auto

deno run -A npm:@tailwindcss/cli \
  -i ../crates/ksbh-ui/static/css/shared.css \
  -o ../crates/ksbh-ui/static/css/style.css

  deno run -A npm:@tailwindcss/cli \
  -i css/base.css \
  -o static/css/style.css
